# Generated by Django 3.1.7 on 2021-03-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210316_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='representation',
            field=models.ImageField(blank=True, upload_to='сategory/', verbose_name='Изображение'),
        ),
    ]
